### PR TITLE
Feature update t3 i81

### PR DESCRIPTION
**Pull request by zmaalick**

### CODE REVIEW

**Review by balazagi — COMMENTED** [review]
To be consistent throughout I suggest to rename the constraint names in section 3.1 and 3.2 like others. Also we want these changes reflected in solution notebooks too.

**Review by balazagi — CHANGES_REQUESTED** [review]
- There is a type in section 2.1 code causing an error
```
# lets print out wnddir_son_mean cube to see its chape
wnddir_son_mean
```
should be (note correction needed in comment as well)
```
# lets print out wndir_son_mean cube to see its chape
wndir_son_mean
```

-  In the same section in the code for plotting in _PlateCarree_ projection, **ax** is not defined so we get the error:
`NameError: name 'ax' is not defined`

- The change in constraint naming is doing the job and is clearer but in my opinion changing of the constraints name would have sufficed 
e.g.` cons1 --> past_cons, cons2 -->present_cons`

**Comment by zmaalick** [comment]
made all the above mentioned changes

**Review by balazagi — APPROVED** [review]
make sure you clear the cell outputs

**Pull request merged**
