### PR TITLE
fix the typo #79

### PR DESCRIPTION
**Pull request by zmaalick**
Fixed the typo: "monthly" to "hourly"

### CODE REVIEW

**Review by balazagi — APPROVED** [review]

**Comment by zmaalick** [comment]
This pull request is merging to master. I will close this and recreate the pull request. But will merge it straight away now

**Comment by balazagi** [comment]
please don't merge I have not approved it yet there are changes needed

**Comment by zmaalick** [comment]
ok
________________________________

**Comment by balazagi** [comment]
sorry I got confused with tutorial 1 changes this is good to go

**Pull request closed without merging**
