### PR TITLE
Release tutorials

### PR DESCRIPTION
**Pull request by zmaalick**
It is the final review to merge into the Master. Please have a look thoroughly.

### CODE REVIEW

**Comment by balazagi** [comment]
I do  my best here but there are a lot of changes in here and as it is the final release I recommend two reviewers.

**Comment by zmaalick** [comment]
Nick has reviewed it while merging it to develop. But he has investigated overall structure.

________________________________

**Review by balazagi — CHANGES_REQUESTED** [review]
I have gone through the changes and from my end looks good but a few cosmetics needs fixing as follow:

- Introduction notebook
Section 3, last paragraph end of line _"...in the tutorials we have only use..."_ either remove "_have_" or change "_use_" to "_used_"
- Tutorial 4, section 3.1
the comment in the third block of code "_Now extract present day_" is misplaced and need moving further down before the time constraint definition 
- typo in the text describing _np.where_
otherise --> otherwise

**Comment by zmaalick** [comment]
Fix the typos. 

It is a good test as now we need to update both: Master and develop

**Pull request merged**
