### PR TITLE
Make a version of the notebooks for the AFR-22 domain

### PR DESCRIPTION
**Pull request by nhsavage**
These are a new set of notebooks, derived from the EAS-22 ones. Some fixes to the notebooks will need to be pushed back to the EAS-22 ones. I will open a separate ticket for these issues.

### CODE REVIEW

**Comment by rosannaamato** [comment]
Having now got my head round git a bit, I think the above 3 commits (primarily afafb6d) fixes #138 (renaming HISTDIR).

**Comment by rosannaamato** [comment]
ab0d48b / 72fed13 (above) address the incorrect method of calculating wetday_count in EAS worksheet 5. I think this fixes #140.

**Comment by rosannaamato** [comment]
Branch reverted to Nick's last commit (cc22230) as I have removed my commits that should have been made in a separate branch. Apologies, tidy again.

**Comment by nhsavage** [comment]
> General comment I think one of the main possible stumbling blocks is the underlying assumption about which directory the user is in, I would be tempted at least at the start of every worksheet to add in a pwd or similar so users can check they are in the right directory.

I agree that this is a stumbling block. However I think it has to be addressed on a different issue. The challenge with it is that the path to use will be platform dependent - so some sort of include file with the platform specific needs to be set up. This would also include potentially scripts fetching from S3 buckets or precisrcm and doing the linking.

**Comment by nhsavage** [comment]
> > General comment I think one of the main possible stumbling blocks is the underlying assumption about which directory the user is in, I would be tempted at least at the start of every worksheet to add in a pwd or similar so users can check they are in the right directory.
> 
> I agree that this is a stumbling block. However I think it has to be addressed on a different issue. The challenge with it is that the path to use will be platform dependent - so some sort of include file with the platform specific needs to be set up. This would also include potentially scripts fetching from S3 buckets or precisrcm and doing the linking.

On reflection, I will make this work for the existing VDI set up and I have opened #145 to deal with multiple sets of options for download of data

**Comment by nhsavage** [comment]
Closes #124

**Comment by nhsavage** [comment]
I have now updated to account for the comments apart from the last one "in the first code block of 1.2 I would recommend explicitly cding into the correct directory (to prevent confusion, even though they should already be in it.)" - I want this to be covered in a follow on ticket

**Review by gredmond-mo — APPROVED** [review]

**Review by gredmond-mo — APPROVED** [review]

**Pull request merged**
