### PR TITLE
updated the notebook with azure-relevant instructions and added the  …

### PR DESCRIPTION
**Pull request by balazagi**
- updated instructions related to storage to be azure relevant
- corrected a few typo, a couple of cosmetic changes and rephrasing of sentences
- uploaded and ran it on azure platform
- added the missing *variables.pdf* file to which we link
**Note**: we nee to agree where this pdf file is finally to reside for workshop and update the link accordingly. One option could be to link it to its github version on master once all merged!

### CODE REVIEW

**Review by nhsavage — CHANGES_REQUESTED** [review]
This only seems to have the extra variableslist.pdf file and not the other changes?

**Comment by balazagi** [comment]
> This only seems to have the extra variableslist.pdf file and not the other changes?

sorry missed the git add bit! just did and pushed try again please.

**Comment by hsteptoe** [comment]
For consistency, can you please also update the `README.md` with a little info about accessing data for the CSSP notebooks.  Further details about the CSSP data access should be added into the `/data/DATA-ACCESS.md`.

**Comment by hsteptoe** [comment]
I've just added some updates from the `master` into this branch so you can edit the latest version of `DATA-ACCESS.md`

**Review by nhsavage — APPROVED** [review]
We will need to revisit the question of the kernel once we have a solution for this

**Pull request merged**
