### PR TITLE
notebook with proposed solutions to tasks and excercises

### PR DESCRIPTION
**Pull request by balazagi**

### CODE REVIEW

**Review by nhsavage — COMMENTED** [review]
1. should this be in a new notebook (as Zubair has done for the others?)
2. 
2. for the solutions would it be better to leave the output in the notebook?
3.  some of the lines are very long - please split up

**Comment by balazagi** [comment]
> 1. should this be in a new notebook (as Zubair has done for the others?)
> 2. for the solutions would it be better to leave the output in the notebook?
> 3. some of the lines are very long - please split up

about 3. do you mean some of the solution cells have too many lines in them or specific lines in some cells are too long. If latter could you please be more specific.

**Comment by nhsavage** [comment]
I mean that certain lines are too long. 
mainly in Excercise 3 this comment

`#Since grid_latitude and grid_longitude were both point coordinates we must guess bound positions for them in order to calculate the area of the grid boxes
`
and this line:
`
precipitation_mean = precipitation_cube.collapsed(['grid_longitude', 'grid_latitude'], iris.analysis.MEAN, weights=grid_areas)`

both of which are too wide for the notebook cells

**Comment by balazagi** [comment]
> I mean that certain lines are too long.
> mainly in Excercise 3 this comment
> 
> `#Since grid_latitude and grid_longitude were both point coordinates we must guess bound positions for them in order to calculate the area of the grid boxes `
> and this line:
> ` precipitation_mean = precipitation_cube.collapsed(['grid_longitude', 'grid_latitude'], iris.analysis.MEAN, weights=grid_areas)`
> 
> both of which are too wide for the notebook cells

thanks I have made those changes. I noticed that this is the case elsewhere in notebooks too. I make a new issue to fix these in other notebooks when there is time!

**Comment by nhsavage** [comment]
thanks. I now approve these changes.

**Pull request merged**
