### PR TITLE
update notebook to use Azure Blob Storage

### PR DESCRIPTION
**Pull request by nhsavage**
This new version of tutorial 1 works from the data in our new Azure Blob store. It does not include the key but prompts the user to set this

### CODE REVIEW

**Comment by nhsavage** [comment]
further changes made to branch and pushed

**Comment by balazagi** [comment]
there are two more minor changes:

- a duplicate word in second paragraph of section 1.2 _"This makes use of the Azure Azure Blob Storage..."_
- a typo in the Exercise 5 at the end of notebook 

otherwise is good to go in my view.

**Comment by nhsavage** [comment]
change made

**Comment by hsteptoe** [comment]
Please also consider if this is worth bumping the release number up a notch - it sounds like it probably is (ie. to v2.1)

**Comment by nhsavage** [comment]
re Hamish's comment - we probably should do that, but I think only once a. we have completed all the changes, b. we have pushed them to master (this PR is against develop)

**Comment by balazagi** [comment]
> re Hamish's comment - we probably should do that, but I think only once a. we have completed all the changes, b. we have pushed them to master (this PR is against develop)

I suggest we create a separate issue for this and have it done when we are ready!

**Review by balazagi — APPROVED** [review]
Looks good to go now

**Pull request merged**
