### PR TITLE
Feature solution t4 i57

### PR DESCRIPTION
**Pull request by zmaalick**
Section 3 task and Exercise are very similar. Can you suggest something different for exercises?

### CODE REVIEW

**Comment by nhsavage** [comment]
This solution doesn't solve the problem I think it is supposed to. Probably the task needs explaining better.

My interpretation of the question is "what percentage of all of the precipitation in this period fell on days when there was heavy rain i.e. => 95th Percentile. 

I would break the exercise part 1 down some more into these steps:

1. load the daily data for the period 1981-2010  and extract Shanghai
2. find the total rainfall 
3. find the 95th percentile of daily rainfall for the period
4. find the sum of the rainfall on days when the precip > 95th percentile
5. find the percentage of all of the precipitation in this period which fell on days when there was heavy rain

Then repeat for 1851-1880 (note there is a typo in the exercise - should be 1851, actually says 1951)

**Comment by zmaalick** [comment]
Point 4 is a bit misunderstood to me:
find the sum of the rainfall on days when the precip > 95th percentile

what does "sum of rainfall" means? is it like point 2: total rainfall? 

if so, then with 95p cube, we do not have time dimension to calculate the  number of wet days.
present_precip_shanghai_pc95 = present_precip_shanghai.collapsed('time', iris.analysis.PERCENTILE, percent=95.)

Seems like I misunderstood.

**Comment by zmaalick** [comment]
Updated with the suggested changes

**Comment by nhsavage** [comment]
I have had a go at my own version of this, as I don't think your branch is aligned with how I interpet the quesiton. See https://github.com/MetOffice/PyPRECIS/tree/feature_solution_ns_t4_i57

**Review by nhsavage — CHANGES_REQUESTED** [review]
one final thing sorry, I left some debugging output in the notebooks. Can you please remove the bits that print the grid coordinates but retain the guess bounds which is needed in order to do the difference

**Comment by zmaalick** [comment]
> one final thing sorry, I left some debugging output in the notebooks. Can you please remove the bits that print the grid coordinates but retain the guess bounds which is needed in order to do the difference

I have already done it .. 
In this solution notebook, I didn't put coordinate prints and all guess bounds are fine

**Review by nhsavage — APPROVED** [review]

**Comment by nhsavage** [comment]
sorry about that - I was looking at the wrong location. Approved

**Pull request merged**
